// Discount codes, one per brand, from wellhub.com.au/deals (September 2026).
export const deals = [
  { brand: "Youfoodz", group: "ready", offer: "Up to $200 off your first 5 boxes", code: "WH200", tags: ["New customers"] },
  { brand: "HelloFresh", group: "kit", offer: "Up to $200 off your first 6 boxes", code: "WELLHUBFRESH", tags: ["New customers", "Family"] },
  { brand: "Soulara", group: "ready", offer: "$240 off across 8 weeks", code: "SOUL240OFF", tags: ["Vegan"] },
  { brand: "MACROS", group: "ready", offer: "$150 off across your first 5 orders", code: "HUB150", tags: ["High protein"] },
  { brand: "My Muscle Chef", group: "ready", offer: "Up to $120 off your first 6 orders", code: "WELLHUB120", tags: ["High protein"] },
  { brand: "QuiteLike", group: "kit", offer: "Up to $200 off your first 5 boxes", code: "WELLHUB200", tags: ["NSW, VIC, ACT, QLD"] },
  { brand: "EveryPlate", group: "kit", offer: "Meals from $2.19 per plate", code: "WELLPLATE", tags: ["Budget"] },
  { brand: "Pam Pam Asian Meals", group: "ready", offer: "15% off your first order", code: "WELLHUB15", tags: ["New customers"] },
  { brand: "Be Fit Food", group: "ready", offer: "10% off your first order", code: "WELLHUB10", tags: ["Weight loss"] },
  { brand: "Garden of Vegan", group: "ready", offer: "$30 off a one-off purchase", code: "WELLHUB30", tags: ["Vegan"] },
  { brand: "HerbiDoor", group: "ready", offer: "10% off your order", code: "WELLHUBAU", tags: ["Vegan"] },
  { brand: "Dietlicious", group: "ready", offer: "$30 off your first order", code: "AFF-MFGK", tags: ["Dairy free"] },
  { brand: "The St. Food Co.", group: "ready", offer: "10% off your first order", code: "WELLHUB10", tags: ["New customers"] },
  { brand: "Vitable", group: "supp", offer: "40% off your first month ($20 min. spend)", code: "VITWELSB40", tags: ["Vitamins"] },
  { brand: "SWIISH", group: "supp", offer: "15% off storewide", code: "WELLHUB", tags: ["Wellness"] },
  { brand: "Bush Tucker Blends", group: "supp", offer: "10% off your first order", code: "WELLHUB10", tags: ["Wholefood"] },
  { brand: "Butcher Crowd", group: "other", offer: "$10 off your first box, plus a free cut per box for 12 months", code: "WLLHB10", tags: ["Meat box"] },
  { brand: "TinyBeets Foods", group: "other", offer: "15% off your first order", code: "WELLHUB15", tags: ["Baby & toddler"] },
];
